### ISSUE TITLE
Bind context to call of this._super.included() in index.js

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-object-details#50]
or just remove all together

**Comment by notmessenger** [comment]
Removing

```
  included: function (app) {
    this._super.included(app)
  }
```

because no additional logic is being performed or changing it to

```
  included: function (app) {
    this._super.included.apply(this, app)
  }
```

both result in the error of

```
Cannot read property 'import' of undefined
TypeError: Cannot read property 'import' of undefined
    at Class.included (/ember-frost-object-details/node_modules/ember-simple-uuid/index.js:10:13)
    at Class.superWrapper [as included] (/ember-frost-object-details/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
...
```


This is due to this code in _ember-simple-uuid/index.js_

```
  included: function (app) {
    this._super.included(app);

    this.app.import(app.bowerDirectory + '/node-uuid/uuid.js');
  }
```

Changing `this.app.import(app.bowerDirectory + '/node-uuid/uuid.js');` to `app.import(app.bowerDirectory + '/node-uuid/uuid.js');` then results in the error of

```
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open '/ember-frost-object-details/tmp/source_map_concat-input_base_path-ud0pV1KV.tmp/undefined/node-uuid/uuid.js'
```

the important part here being the `undefined` in the path where `app.bowerDirectory` was expected to be a value.  Changing `this._super.included(app);` to `this._super.included.apply(this, app);` does not resolve this either.

The best I have been able to piece together is that

> nested addons don't have the bowerDirectory property that allows to locate bower assets
- https://github.com/ember-cli/ember-cli/pull/6111

This issue was abandoned in favor of this RFC - https://github.com/ember-cli/rfcs/pull/63 - which itself became abandoned.

The RFC talks about `_findHost` here - https://github.com/ember-cli/rfcs/pull/63#r73812418 - and implementing this logic in _ember-simple-uuid/index.js_ then resolves this issue:

```
  _findHost() {
    let current = this;
    let app;

    // Keep iterating upward until we don't have a grandparent.
    // Has to do this grandparent check because at some point we hit the project.
    do {
      app = current.app || app;
    } while (current.parent.parent && (current = current.parent));

    return app;
  },

  included: function () {
    var app = this._findHost()

    app.import(app.bowerDirectory + '/node-uuid/uuid.js');
  }
```

indicating that the problem can likely be addressed by upgrading the version of Ember CLI in `ember-simple-uuid` beyond it's current `2.3.0`.

**Comment by notmessenger** [comment]
The merging of https://github.com/ciena-frost/ember-frost-object-details/pull/52 should resolve the problems being experienced in addressing this issue.
